# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'impact_table.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DlgImpacts(object):
    def setupUi(self, DlgImpacts):
        DlgImpacts.setObjectName("DlgImpacts")
        DlgImpacts.resize(400, 300)
        self.tblImpacts = QtWidgets.QTableWidget(DlgImpacts)
        self.tblImpacts.setGeometry(QtCore.QRect(10, 10, 381, 271))
        self.tblImpacts.setAlternatingRowColors(True)
        self.tblImpacts.setObjectName("tblImpacts")
        self.tblImpacts.setColumnCount(3)
        self.tblImpacts.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblImpacts.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblImpacts.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblImpacts.setHorizontalHeaderItem(2, item)

        self.retranslateUi(DlgImpacts)
        QtCore.QMetaObject.connectSlotsByName(DlgImpacts)

    def retranslateUi(self, DlgImpacts):
        _translate = QtCore.QCoreApplication.translate
        DlgImpacts.setWindowTitle(_translate("DlgImpacts", "Impacts Table"))
        item = self.tblImpacts.horizontalHeaderItem(0)
        item.setText(_translate("DlgImpacts", "Project"))
        item = self.tblImpacts.horizontalHeaderItem(1)
        item.setText(_translate("DlgImpacts", "Type"))
        item = self.tblImpacts.horizontalHeaderItem(2)
        item.setText(_translate("DlgImpacts", "Distance"))
